# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
	
posters = Poster.create([{image_url:"http://cdn.mos.totalfilm.com/images/e/et-alien.jpg", user_id:"1", blurb:"This alien eats more than Reeses Pieces", title1:"E.T.", title2:"Alien", mash_title:"A.L.I.E.N"},
	{image_url:"http://www.bitrebels.com/wp-content/uploads/2011/10/Star-Wars-Mashup-Movie-Posters-8.jpg", user_id:"2", blurb:"Po, I am your father!", title1:"Star Wars", title2:"Kung Fu Panda", mash_title:"Panda Wars"},
	{image_url:"http://www.empireonline.com/images/features/movie-poster-mash-up/muppets/1.jpg", user_id:"1", blurb:"Don't take my cookies!!", title1:"One Flew Over The Cukoo's Nest", title2:"Sesame Street", mash_title:"One Flew Over The Cookies Nest"},
	{image_url:"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTx96RsNmmYibXJyx7udRnMLYhvMgIDNneTDGUqrRO8NqSoAnC68w", user_id:"2", blurb:"Wonderland in outer space.", title1:"Alice In Wonderland", title2:"Star Wars", mash_title:"Starwars in Wonderland"},
	{image_url:"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRe_RMep09IUMkrJCdyaJBkx5h5HaZwMzQVAUTJorxAnmWXfFvpQA", user_id:"1", blurb:"You will be unprepared for all the punching and the love.", title1:"Sucker Punch", title2:"Punch Drunk Love", mash_title:"Sucker Punch Drunk Love"},
	{image_url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWZoSA3JN1x-brLsb0r2WdRsxCcolxgna7_nFzJd90LKBi3wTL", user_id:"1", blurb:"Don't talk about the breakfast fight club.", title1:"Breakfast Club", title2:"Fight Club", mash_title:"The Breakfast Fight Club"},
	{image_url:"http://cdn.smosh.com/sites/default/files/bloguploads/movie-mashup-300-summer-1.jpg", user_id:'2', blurb:"THIS IS ROMANTIC!", title1:"300", title2:"500 Days of Summer", mash_title:"300 Days of Summer"},
	{image_url:"http://tutorials-share.com/wp-content/uploads/2011/08/movie-poster-mashups-design-023.jpg", user_id:'1', blurb:"The one donut to rule them all.", title1:"The Simpsons Movie", title2:"The Lord of the Rings", mash_title:"Lord of the Rings" },
	{image_url:"http://bashooka.com/wp-content/uploads/2013/01/movie-poster-mashups-4.jpg", user_id:'2', blurb:'No Watch, No Glory', title1:"The Men Who Stare At Goats", title2:"The Watchmen", mash_title:"The Men Who Stare At Watches"},
	{image_url:"http://cdn.smosh.com/sites/default/files/ftpuploads/bloguploads/movie-mashup-shield-of-dreams.jpg", user_id:"1", blurb:"If you build it, they will avenge", title1:"The Avengers", title2:"The Field of Dreams", mash_title:"S.H.I.E.L.D. of Dreams"}, 
	{image_url:"http://www.rovalocity.com/storage/Movie%20Poster%20-%20Snakes%20on%20a%20Plane.jpg?__SQUARESPACE_CACHEVERSION=1407166120916", user_id:"1", blurb:'I am tired of these monkey biting snakes on this monday to friday plane', title1:"Airplane", title2:"Snakes on a Plane", mash_title:"snakes on an Airplane"},	
	{image_url:"http://cdn.mos.totalfilm.com/images/t/titanic-300.jpg", user_id:"2", blurb:"Our horderves will blot out the sky", title1:"300", title2:"Titanic", mash_title:"Titanic"}
	])





stories = Story.create([{title1:"Toy Story", title2:"Terminator", mash_title:"Toyminator", content:"Pitchfork pop-up art party, aesthetic distillery Marfa Echo Park mixtape mumblecore. Mustache asymmetrical quinoa Pitchfork leggings, ethical aesthetic banjo mumblecore Tonx hashtag umami Echo Park fixie chillwave. Banh mi Portland Carles, bespoke mixtape distillery wayfarers retro shabby chic ugh Intelligentsia 3 wolf moon 90's kitsch. Lo-fi literally yr, next level sustainable pop-up +1 Cosby sweater keytar photo booth PBR&B quinoa gluten-free squid. Cosby sweater kitsch ugh banjo McSweeney's wolf. Intelligentsia Bushwick 8-bit gluten-free. Dreamcatcher sustainable lomo, biodiesel blog 90's Odd Future Vice.", user_id:"2"},
	{title1:"Indiana Jones", title2:"Bridget Jones' Diary", mash_title:"Indiana Jones' Diary", content:"Ennui direct trade fingerstache drinking vinegar Marfa stumptown Helvetica. Post-ironic Intelligentsia +1 Godard Kickstarter distillery. Bicycle rights locavore twee, McSweeney's pop-up 8-bit four loko mumblecore chambray. Next level master cleanse hoodie, pork belly plaid mumblecore food truck scenester. Single-origin coffee Helvetica Pinterest, wayfarers art party VHS fanny pack biodiesel keytar four loko twee Wes Anderson. Crucifix tousled fixie, disrupt umami cred beard leggings wayfarers 3 wolf moon Pinterest chillwave banh mi. Chillwave Intelligentsia art party, XOXO direct trade jean shorts DIY twee bespoke gastropub High Life letterpress biodiesel.", user_id:"1"},
	{title1:"Alice in Wonderland", title2:"Zombieland", mash_title:"Alice in Zombieland", content:"Williamsburg Pitchfork before they sold out hoodie, readymade four loko PBR&B post-ironic vinyl freegan kogi mumblecore selvage normcore. Small batch street art jean shorts synth squid. Sustainable fingerstache you probably haven't heard of them direct trade try-hard post-ironic, cray synth chillwave. Try-hard pickled sustainable iPhone craft beer Tumblr. PBR&B try-hard meggings, meh blog whatever chia pickled gluten-free High Life XOXO McSweeney's. 3 wolf moon shabby chic post-ironic, High Life kitsch 8-bit Pitchfork small batch organic hashtag typewriter. Pickled Pinterest salvia banjo.", user_id:"1"},
	{title1:"Teenage Mutant Ninja Turtles", title2:"Happy Gilmore", mash_title:"Teenage Mutant Ninja Golfers", content:"Typewriter mumblecore raw denim Vice. Austin cardigan drinking vinegar, semiotics you probably haven't heard of them occupy brunch chia slow-carb sustainable polaroid bespoke typewriter put a bird on it. Williamsburg butcher gentrify fap cliche. Biodiesel asymmetrical distillery VHS, Williamsburg Thundercats fashion axe brunch next level Schlitz. Photo booth authentic bitters craft beer, normcore sriracha artisan Kickstarter fixie gentrify forage. Tousled bicycle rights Wes Anderson +1 Austin. Farm-to-table paleo Brooklyn beard.", user_id:"2"},
	{title1:"How to Train Your Dragon 2", title2:"Muppets Most Wanted", mash_title:"How to Train Your Muppet 2", content:"Flexitarian fingerstache mumblecore, retro meggings forage fap squid artisan drinking vinegar stumptown fixie wayfarers quinoa. Stumptown cray typewriter Pinterest aesthetic, kale chips Truffaut Marfa cardigan. Forage chambray Brooklyn pork belly, Marfa mumblecore letterpress cornhole 3 wolf moon post-ironic put a bird on it Williamsburg semiotics Schlitz. PBR&B wayfarers kogi cliche. Fixie hashtag sriracha kale chips you probably haven't heard of them freegan. Schlitz DIY deep v, yr street art freegan retro. Deep v normcore yr, chia flexitarian single-origin coffee sriracha Intelligentsia fingerstache stumptown Neutra farm-to-table Shoreditch mixtape.", user_id:"1"},
	{title1:"Hurcules", title2:"Need for Speed", mash_title:"The Need for Mass", content:"Paleo tattooed literally Helvetica roof party. 90's flannel direct trade before they sold out tattooed. Marfa chia cornhole selvage meggings messenger bag. Brunch Pitchfork photo booth, wolf food truck sartorial Wes Anderson. Yr brunch Pitchfork retro squid mixtape, sriracha Carles biodiesel asymmetrical. Polaroid Shoreditch XOXO gluten-free Truffaut vegan. Chambray XOXO swag, whatever jean shorts flexitarian wolf.", user_id:"1"}
	])

comments = Comment.create([{content:"This is the best mash-up website ever!!!", commentable_id:1, commentable_type:"poster"},
	{content:"This is the best mash-up website ever!!!", commentable_id:2, commentable_type:"story"},
	{content:"This is the best mash-up website ever!!!", commentable_id:3, commentable_type:"poster"}])

